#############################################################################
# Makefile for building: cube
# Generated by qmake (2.01a) (Qt 4.8.7) on: ven. sept. 28 10:27:40 2018
# Project:  cube.pro
# Template: app
# Command: /home/gg/miniconda3/bin/qmake -o Makefile cube.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../miniconda3/mkspecs/linux-g++ -I. -I../../../../miniconda3/include/qt/QtCore -I../../../../miniconda3/include/qt/QtGui -I../../../../miniconda3/include/qt -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/gg/miniconda3/lib
LIBS          = $(SUBLIBS)  -L/home/gg/miniconda3/lib -lQtGui -L/home/gg/miniconda3/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/gg/miniconda3/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwidget.cpp \
		geometryengine.cpp moc_mainwidget.cpp \
		qrc_shaders.cpp \
		qrc_textures.cpp
OBJECTS       = main.o \
		mainwidget.o \
		geometryengine.o \
		moc_mainwidget.o \
		qrc_shaders.o \
		qrc_textures.o
DIST          = ../../../../miniconda3/mkspecs/common/unix.conf \
		../../../../miniconda3/mkspecs/common/linux.conf \
		../../../../miniconda3/mkspecs/common/gcc-base.conf \
		../../../../miniconda3/mkspecs/common/gcc-base-unix.conf \
		../../../../miniconda3/mkspecs/common/g++-base.conf \
		../../../../miniconda3/mkspecs/common/g++-unix.conf \
		../../../../miniconda3/mkspecs/qconfig.pri \
		../../../../miniconda3/mkspecs/modules/qt_webkit_version.pri \
		../../../../miniconda3/mkspecs/features/qt_functions.prf \
		../../../../miniconda3/mkspecs/features/qt_config.prf \
		../../../../miniconda3/mkspecs/features/exclusive_builds.prf \
		../../../../miniconda3/mkspecs/features/default_pre.prf \
		../../../../miniconda3/mkspecs/features/release.prf \
		../../../../miniconda3/mkspecs/features/default_post.prf \
		../../../../miniconda3/mkspecs/features/shared.prf \
		../../../../miniconda3/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../miniconda3/mkspecs/features/warn_on.prf \
		../../../../miniconda3/mkspecs/features/qt.prf \
		../../../../miniconda3/mkspecs/features/unix/thread.prf \
		../../../../miniconda3/mkspecs/features/moc.prf \
		../../../../miniconda3/mkspecs/features/resources.prf \
		../../../../miniconda3/mkspecs/features/uic.prf \
		../../../../miniconda3/mkspecs/features/yacc.prf \
		../../../../miniconda3/mkspecs/features/lex.prf \
		../../../../miniconda3/mkspecs/features/include_source_dir.prf \
		cube.pro
QMAKE_TARGET  = cube
DESTDIR       = 
TARGET        = cube

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cube.pro  ../../../../miniconda3/mkspecs/linux-g++/qmake.conf ../../../../miniconda3/mkspecs/common/unix.conf \
		../../../../miniconda3/mkspecs/common/linux.conf \
		../../../../miniconda3/mkspecs/common/gcc-base.conf \
		../../../../miniconda3/mkspecs/common/gcc-base-unix.conf \
		../../../../miniconda3/mkspecs/common/g++-base.conf \
		../../../../miniconda3/mkspecs/common/g++-unix.conf \
		../../../../miniconda3/mkspecs/qconfig.pri \
		../../../../miniconda3/mkspecs/modules/qt_webkit_version.pri \
		../../../../miniconda3/mkspecs/features/qt_functions.prf \
		../../../../miniconda3/mkspecs/features/qt_config.prf \
		../../../../miniconda3/mkspecs/features/exclusive_builds.prf \
		../../../../miniconda3/mkspecs/features/default_pre.prf \
		../../../../miniconda3/mkspecs/features/release.prf \
		../../../../miniconda3/mkspecs/features/default_post.prf \
		../../../../miniconda3/mkspecs/features/shared.prf \
		../../../../miniconda3/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../miniconda3/mkspecs/features/warn_on.prf \
		../../../../miniconda3/mkspecs/features/qt.prf \
		../../../../miniconda3/mkspecs/features/unix/thread.prf \
		../../../../miniconda3/mkspecs/features/moc.prf \
		../../../../miniconda3/mkspecs/features/resources.prf \
		../../../../miniconda3/mkspecs/features/uic.prf \
		../../../../miniconda3/mkspecs/features/yacc.prf \
		../../../../miniconda3/mkspecs/features/lex.prf \
		../../../../miniconda3/mkspecs/features/include_source_dir.prf \
		/home/gg/miniconda3/lib/libQtGui.prl \
		/home/gg/miniconda3/lib/libQtCore.prl
	$(QMAKE) -o Makefile cube.pro
../../../../miniconda3/mkspecs/common/unix.conf:
../../../../miniconda3/mkspecs/common/linux.conf:
../../../../miniconda3/mkspecs/common/gcc-base.conf:
../../../../miniconda3/mkspecs/common/gcc-base-unix.conf:
../../../../miniconda3/mkspecs/common/g++-base.conf:
../../../../miniconda3/mkspecs/common/g++-unix.conf:
../../../../miniconda3/mkspecs/qconfig.pri:
../../../../miniconda3/mkspecs/modules/qt_webkit_version.pri:
../../../../miniconda3/mkspecs/features/qt_functions.prf:
../../../../miniconda3/mkspecs/features/qt_config.prf:
../../../../miniconda3/mkspecs/features/exclusive_builds.prf:
../../../../miniconda3/mkspecs/features/default_pre.prf:
../../../../miniconda3/mkspecs/features/release.prf:
../../../../miniconda3/mkspecs/features/default_post.prf:
../../../../miniconda3/mkspecs/features/shared.prf:
../../../../miniconda3/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../../miniconda3/mkspecs/features/warn_on.prf:
../../../../miniconda3/mkspecs/features/qt.prf:
../../../../miniconda3/mkspecs/features/unix/thread.prf:
../../../../miniconda3/mkspecs/features/moc.prf:
../../../../miniconda3/mkspecs/features/resources.prf:
../../../../miniconda3/mkspecs/features/uic.prf:
../../../../miniconda3/mkspecs/features/yacc.prf:
../../../../miniconda3/mkspecs/features/lex.prf:
../../../../miniconda3/mkspecs/features/include_source_dir.prf:
/home/gg/miniconda3/lib/libQtGui.prl:
/home/gg/miniconda3/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile cube.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cube1.0.0 || $(MKDIR) .tmp/cube1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cube1.0.0/ && $(COPY_FILE) --parents mainwidget.h geometryengine.h .tmp/cube1.0.0/ && $(COPY_FILE) --parents shaders.qrc textures.qrc .tmp/cube1.0.0/ && $(COPY_FILE) --parents main.cpp mainwidget.cpp geometryengine.cpp .tmp/cube1.0.0/ && (cd `dirname .tmp/cube1.0.0` && $(TAR) cube1.0.0.tar cube1.0.0 && $(COMPRESS) cube1.0.0.tar) && $(MOVE) `dirname .tmp/cube1.0.0`/cube1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cube1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwidget.cpp
moc_mainwidget.cpp: geometryengine.h \
		mainwidget.h
	/home/gg/miniconda3/bin/moc $(DEFINES) $(INCPATH) mainwidget.h -o moc_mainwidget.cpp

compiler_rcc_make_all: qrc_shaders.cpp qrc_textures.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_shaders.cpp qrc_textures.cpp
qrc_shaders.cpp: shaders.qrc \
		fshader.glsl \
		vshader.glsl
	/home/gg/miniconda3/bin/rcc -name shaders shaders.qrc -o qrc_shaders.cpp

qrc_textures.cpp: textures.qrc \
		cube.png
	/home/gg/miniconda3/bin/rcc -name textures textures.qrc -o qrc_textures.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp mainwidget.h \
		geometryengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwidget.o: mainwidget.cpp mainwidget.h \
		geometryengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

geometryengine.o: geometryengine.cpp geometryengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geometryengine.o geometryengine.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

qrc_shaders.o: qrc_shaders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_shaders.o qrc_shaders.cpp

qrc_textures.o: qrc_textures.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_textures.o qrc_textures.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/gg/miniconda3/opengl/cube/ || $(MKDIR) $(INSTALL_ROOT)/home/gg/miniconda3/opengl/cube/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/gg/miniconda3/opengl/cube/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/home/gg/miniconda3/opengl/cube/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/gg/miniconda3/opengl/cube/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/gg/miniconda3/opengl/cube/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

